import type { Metadata } from 'next';
import '../shared/styles/index.scss';
import React from 'react';
import { CssBaseline } from '@mui/material';
import ReduxProvider from '../shared/redux/provider/reduxProvider';

export const metadata: Metadata = {
    title: 'stt Market',
    description: 'Generated by create blog app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReduxProvider>
            <CssBaseline />
            <html lang='en'>
                <body>
                    <div className='wrapper'>{children}</div>
                </body>
            </html>
        </ReduxProvider>
    );
}
